version: '3.8'

services:
   redis:
     image: redis
     ports:
       - "6379:6379"
     command: ["redis-server", "--appendonly", "yes"]
     volumes:
      - ../../swarm/volumes/swarm-vols:/data
     deploy:
       mode: replicated
       replicas: 4
       limits:
         cpus: '0.1'
         memory: 20M

   web:
     image: german2404/counter
     ports:
       - "8000:8000"
     deploy:
       mode: replicated
       replicas: 4
       limits:
         cpus: '0.1'
         memory: 20M


