---
- hosts: all
  vars_files:
    - vars.yml

  tasks:
    - name: Run Gluster Install Commands
      shell: bash glusterfs.sh
      become: yes
    - name: Run Gluster Hosts Commands
      shell: bash glusterconfig.sh
      become: yes

    - name: Install yum utils
      yum:
        name: yum-utils
        state: latest
        force: yes

    - name: Add Docker repo
      get_url:
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docer-ce.repo
      become: yes
      
    - name: Install packages
      yum:
        name: "{{ PACKAGES }}"
        state: present
        update_cache: true
        force: yes

    - name: Add user vagrant to the docker group
      user:
        name: vagrant
        groups: docker
        append: yes