---
- hosts: servers
  become: true
  tasks:
    - yum:
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes
    - yum:
        name:
          - httpd
        state: present
    - service: name=httpd state=started enabled=yes

